name: Racket unit tests
on: [push]

jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: ["8.0", "8.1", "current"]
        racket-variant: ["BC", "CS"]
    steps:
      - name: "Install MPFR"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - uses: Bogdanp/setup-racket@v1.11
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - run: sudo raco pkg update --name math-lib --link --batch --auto math-lib/
      - run: sudo raco pkg install --batch --auto math-test/
      - run: raco test --drdr math-test/
