name: Racket unit tests
on: [push]

jobs:
  build:
    name: "Build and test on Racket"
    runs-on: ubuntu-latest
    steps:
      - name: "Install MPFR"
        run: sudo apt-get update && sudo apt-get install -y libmpfr6 libmpfr-dev
      - uses: Bogdanp/setup-racket@v1.12
        with:
          architecture: x64
          distribution: full
          variant: CS
          version: current
          sudo: never
          dest: '"${HOME}/racket"'
      - uses: actions/checkout@master
      - run: raco pkg update --no-setup --name math-lib --link --batch --auto math-lib/
      - run: raco pkg install --no-setup --scope installation --link --batch --auto math-test/
      - run: raco setup math
      - run: raco test --drdr math-test/
